In [1]:
import dataregistry
from datetime import datetime

In [2]:
temporary_database_dir = "/Users/jzuntz/src/lsst/dataregistry/temp_data"
dr = dataregistry.DataRegistry(root_dir=temporary_database_dir)

# Connecting to the data registry

NERSC is down so we can't demo this now, but once you are set up it's just:

```
dr = DataRegistry()
```

<pre>





    






    
</pre>

# Registering a single data set

In [3]:
example_data = "/Users/jzuntz/src/lsst/TXPipe/data/example/outputs_metadetect"

id1, execution_id1 = dr.register_dataset(
    name = "test_binned_shear_catalog",
    version = "1.0.0",
    description = "My favourite catalog",
    old_location = example_data + "/" + "binned_shear_catalog.hdf5",
)

 <pre>











 </pre>

# Registering a dataset for a project

In [4]:
id2, execution_id2 = dr.register_dataset(
    name = "test_density_map",
    version = "1.0.0",
    description = "My favourite map",
    old_location = example_data + "/" + "density_maps.hdf5",
    owner = "dp2-shear",
    owner_type = "project"
)

 <pre>











 </pre>

# Registering a dataset within an *execution*

In [5]:
config_file = "/Users/jzuntz/src/lsst/TXPipe/examples/metadetect/config.yml"

execution_id = dr.register_execution(
    name = "txpipe-dp2-metadetect-v1",
    description = "First run of TXPipe on metadetect cats for DP2",
    execution_start = datetime.fromisoformat("2026-06-03"),
    input_datasets = [1, 2], # ids of previously-registered datasets
    configuration = config_file,
)

# Add a new file to the execution
id3, _ = dr.register_dataset(
    "test_shear_map",
    "1.0.0",
    description="My shear map",
    owner="dp2-shear",
    owner_type="project",
    old_location=example_data + "/" + "source_maps.hdf5",
    execution_id=execution_id,
)

 <pre>











 </pre>

# Simple queries

In [6]:
datasets = dr.simple_query(
    owner="dp2-shear",
    columns=["dataset_id", "name", "description"],
    return_format="dataframe")

print(datasets.loc[0]["path"])

datasets

/Users/jzuntz/src/lsst/dataregistry/temp_data/project/dp2-shear/.gen_paths/test_density_map_1.0.0/density_maps.hdf5

,dataset_id,name,description,path
0,2,test_density_map,My favourite map,/Users/jzuntz/src/lsst/dataregistry/temp_data/...
1,3,test_shear_map,My shear map,/Users/jzuntz/src/lsst/dataregistry/temp_data/...

 <pre>











 </pre>

# Full query syntax

In [7]:
f1 = dr.query.gen_filter("dataset.name", "~=", "*map")
f2 = dr.query.gen_filter("version_string", "=", "1.0.0")
dr.find_datasets(
    property_names=["dataset.dataset_id", "dataset.name"],
    filters=[f1,f2],
    return_format='DataFrame',
)

   dataset.dataset_id      dataset.name
0                   2  test_density_map
1                   3    test_shear_map